### PR TITLE
Use npm version from package engines

### LINKED ISSUE #172: Build failure
npmbuildbot fails to build when npm v7 should be used (e.g. https://github.com/nextcloud/photos/pull/826) but instead uses the default version bundled with node lts which is v6 currently.

A solution would be to install the npm version specified in the `engines` field of package.json :)

Will be resolved by https://github.com/nextcloud/.github/pull/7 and will deprecate npmbuildbot

### PR DESCRIPTION
**Pull request by Pytal**
Closes #172 

@skjnldsv

### CODE REVIEW

**Comment by skjnldsv** [comment]
I'm not sure tbh, I want to deprecate this so I don't have to aintain this runtime bot.
This is much more complex than the action we have :thinking:

**Comment by Pytal** [comment]
> I'm not sure tbh, I want to deprecate this so I don't have to aintain this runtime bot.
> This is much more complex than the action we have 🤔

I like not having to build locally and make the CI build and commit as an opt-in, right now the [node workflow](https://github.com/nextcloud/server/blob/c42385ef0fb29a307de091e2a980bbce6c3f5d31/.github/workflows/node.yml) builds but doesn't commit. If we want to deprecate this should we make a new opt-in workflow which builds and commits?

**Comment by skjnldsv** [comment]
> I like not having to build locally and make the CI build and commit as an opt-in

This is more about https://github.com/nextcloud/.github/pull/7
Not about the node.yml action

**Comment by Pytal** [comment]
> This is more about [nextcloud/.github#7](https://github.com/nextcloud/.github/pull/7)
> Not about the node.yml action

I see, looks good 👍 should've remembered that one 😅

**Comment by skjnldsv** [comment]
Seeing the amount of frustration, and until the token issue is fixed, let's do this

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Hum, this creates a race condition if two tasks are being sent at the same time with different npm versions.
One will install npm7 and the other npm6, then there will be a conflict

**Comment by Pytal** [comment]
> Hum, this creates a race condition if two tasks are being sent at the same time with different npm versions.
> One will install npm7 and the other npm6, then there will be a conflict

Damn :(

**Comment by Pytal** [comment]
> Hum, this creates a race condition if two tasks are being sent at the same time with different npm versions.
> One will install npm7 and the other npm6, then there will be a conflict

Damn :( 🤔

**Pull request merged**
