### PR TITLE
Allow working on fork PRs with allow edits from maintainers

### LINKED ISSUE #19: Does not work on forks

### PR DESCRIPTION
**Pull request by gary-kim**
Closes #19 

Hasn't been tested yet. Let me set up to test.

EDIT: Tested: https://github.com/gary-kim/github-app-test-repo/pull/2

### CODE REVIEW

**Comment by skjnldsv** [comment]
Testing ok?

**Comment by gary-kim** [comment]
Yep, seems to work: https://github.com/gary-kim/github-app-test-repo/pull/2

**Comment by skjnldsv** [comment]
@rullzer can you pull latest bot tomorrow (or in a few minutes when docker hub finish building the update? :) )

**Comment by rullzer** [comment]
> @rullzer can you pull latest bot tomorrow (or in a few minutes when docker hub finish building the update? :) )

done

**Pull request merged**
